language: php

env:
  - NETTE=default # 2.3 dev
  - NETTE=nette-2.3

php:
  - 5.6
  - 7.0

before_install:
  - composer self-update

install:
  - mkdir -p vendor/bin
  - wget -O vendor/bin/composer-nette https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php vendor/bin/composer-nette
  - composer install --no-interaction --prefer-source

script: vendor/bin/tester -p php -c ./tests/php.ini-unix ./tests/XRuffTests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
